//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaspiShop.XMLService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XMLService.IXMLService")]
    public interface IXMLService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IXMLService/CreateXML")]
        void CreateXML(int purchaseID, string email);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IXMLService/CreateXML")]
        System.Threading.Tasks.Task CreateXMLAsync(int purchaseID, string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IXMLServiceChannel : KaspiShop.XMLService.IXMLService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XMLServiceClient : System.ServiceModel.ClientBase<KaspiShop.XMLService.IXMLService>, KaspiShop.XMLService.IXMLService {
        
        public XMLServiceClient() {
        }
        
        public XMLServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XMLServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XMLServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XMLServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateXML(int purchaseID, string email) {
            base.Channel.CreateXML(purchaseID, email);
        }
        
        public System.Threading.Tasks.Task CreateXMLAsync(int purchaseID, string email) {
            return base.Channel.CreateXMLAsync(purchaseID, email);
        }
    }
}
