//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaspiShop.CustomerAddressService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoppingDetailsDTO", Namespace="http://schemas.datacontract.org/2004/07/WCFShopService.Services")]
    [System.SerializableAttribute()]
    public partial class ShoppingDetailsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerAddressService.ICustomerAddressService")]
    public interface ICustomerAddressService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerAddressService/Get", ReplyAction="http://tempuri.org/ICustomerAddressService/GetResponse")]
        KaspiShop.CustomerAddressService.ShoppingDetailsDTO Get(int businessEntityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerAddressService/Get", ReplyAction="http://tempuri.org/ICustomerAddressService/GetResponse")]
        System.Threading.Tasks.Task<KaspiShop.CustomerAddressService.ShoppingDetailsDTO> GetAsync(int businessEntityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerAddressService/GetStateProvince", ReplyAction="http://tempuri.org/ICustomerAddressService/GetStateProvinceResponse")]
        int GetStateProvince(string city, string countryCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerAddressService/GetStateProvince", ReplyAction="http://tempuri.org/ICustomerAddressService/GetStateProvinceResponse")]
        System.Threading.Tasks.Task<int> GetStateProvinceAsync(string city, string countryCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerAddressServiceChannel : KaspiShop.CustomerAddressService.ICustomerAddressService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerAddressServiceClient : System.ServiceModel.ClientBase<KaspiShop.CustomerAddressService.ICustomerAddressService>, KaspiShop.CustomerAddressService.ICustomerAddressService {
        
        public CustomerAddressServiceClient() {
        }
        
        public CustomerAddressServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerAddressServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerAddressServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerAddressServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KaspiShop.CustomerAddressService.ShoppingDetailsDTO Get(int businessEntityID) {
            return base.Channel.Get(businessEntityID);
        }
        
        public System.Threading.Tasks.Task<KaspiShop.CustomerAddressService.ShoppingDetailsDTO> GetAsync(int businessEntityID) {
            return base.Channel.GetAsync(businessEntityID);
        }
        
        public int GetStateProvince(string city, string countryCode) {
            return base.Channel.GetStateProvince(city, countryCode);
        }
        
        public System.Threading.Tasks.Task<int> GetStateProvinceAsync(string city, string countryCode) {
            return base.Channel.GetStateProvinceAsync(city, countryCode);
        }
    }
}
