//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWCFClient.TestMQ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestMQ.ITestMQ")]
    public interface ITestMQ {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITestMQ/Process")]
        void Process(string data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITestMQ/Process")]
        System.Threading.Tasks.Task ProcessAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestMQChannel : TestWCFClient.TestMQ.ITestMQ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestMQClient : System.ServiceModel.ClientBase<TestWCFClient.TestMQ.ITestMQ>, TestWCFClient.TestMQ.ITestMQ {
        
        public TestMQClient() {
        }
        
        public TestMQClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestMQClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestMQClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestMQClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Process(string data) {
            base.Channel.Process(data);
        }
        
        public System.Threading.Tasks.Task ProcessAsync(string data) {
            return base.Channel.ProcessAsync(data);
        }
    }
}
